version: 2.1
jobs:
  deploy:
    executor:
      name: node/default
      tag: '13'
    steps:
      - node/with-cache:
          steps:
            - run: yarn add caprover
      - checkout
      - run: yarn deploy

workflows:
  version: 2
  common:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master

orbs:
  node: circleci/node@1.1